name: owl
channels:
- conda-forge
- defaults
dependencies:
- pip
- python>=3.7,<3.10
- pywps>=4.5.1,<4.6
- jinja2
- click
- psutil
# tests
- pytest
# data fetch
- cdsapi
# visualisation
- matplotlib
# data analysis
- netCDF4
- cdo # avoidable if possible
- joblib
