name: owl
channels:
- conda-forge
# - defaults
dependencies:
- pip
- python
- pywps>=4.5.1,<4.6
- jinja2
- click
- psutil
# tests
- pytest
# data fetch
# - cdsapi
# visualisation
- matplotlib
- cartopy
# data analysis
- netCDF4
- joblib
- xarray
- scipy
- scikit-learn
# - python-cdo
# - cdo # avoidable if possible
